#!/bin/bash
cp trojan.gemspec trojan.gemspec.backup
sed -i.bak s/0.0.0/$1/g trojan.gemspec
sed -i.bak s/2001-01-01/`date +%Y-%m-%d`/g trojan.gemspec
gem build trojan.gemspec
mv trojan.gemspec.backup trojan.gemspec
gem push trojan-$1.gem
git tag -a v$1 -m "Release v$1"
git push origin --tags
