#!/bin/bash
cp rixml.gemspec rixml.gemspec.backup
sed -i.bak s/0.0.0/$1/g rixml.gemspec
sed -i.bak s/2001-01-01/`date +%Y-%m-%d`/g rixml.gemspec
gem build rixml.gemspec
mv rixml.gemspec.backup rixml.gemspec
gem push rixml-$1.gem
git tag -a v$1 -m "Release v$1"
git push origin --tags
